const wordList = getWords();

$('body').append(`<div id="words" style="background:white"></div>`);

function submitWord(word) {
    $('#inputChat').val(word);
    $('#formChat').submit();
}

$('#currentWord').bind('DOMSubtreeModified', () => {
    $('#words').html(``);

    const hint = $('#currentWord').text();
    const regexHint = hint.replaceAll('_', '\\S');
    const regex = new RegExp(`^${regexHint}$`);

    const matchesHtml = wordList
        .filter(word => regex.test(word))
        .map(word => `<a href="javascript:submitWord('${word}')" style="color:black">${word}</a>`)
        .join('<br>');

    $('#words').html(matchesHtml);
});


function getWords() {
    return [
        'Vin Diesel',
        'Daffy Duck',
        'Batman',
        'Patrick',
        'Darwin',
        'William Wallace',
        'Barack Obama',
        'Mark Zuckerberg',
        'JayZ',
        'Dora',
        'Ferrari',
        'Tweety',
        'Donald Duck',
        'Pumba',
        'Zeus',
        'Shrek',
        'Steve Jobs',
        'Hollywood',
        'Elsa',
        'Elon Musk',
        'Robbie Rotten',
        'Flash',
        'Grinch',
        'Ikea',
        'Donald Trump',
        'Terminator',
        'Sydney Opera House',
        'Angry Birds',
        'BMW',
        'Minion',
        'James Bond',
        'Australia',
        'Antarctica',
        'AC/DC',
        'Jackie Chan',
        'America',
        'Mercury',
        'Mercedes',
        'Amsterdam',
        'Peppa Pig',
        'Nemo',
        'London Eye',
        'Christmas',
        'Ireland',
        'Apple',
        'Israel',
        'Hulk',
        'Africa',
        'Kermit',
        'Italy',
        'Medusa',
        'Suez Canal',
        'Frankenstein',
        'Fanta',
        'Tails',
        'Morgan Freeman',
        'Iron Man',
        'Discord',
        'Cookie Monster',
        'Happy Meal',
        'Rick',
        'Tooth Fairy',
        'Popsicle',
        'Bill Gates',
        'Scooby Doo',
        'Aladdin',
        'Facebook',
        'Dexter',
        'Bambi',
        'Xbox',
        'Pokemon',
        'Skype',
        'Google',
        'Germany',
        'Garfield',
        'New Zealand',
        'Twitter',
        'Great Wall',
        'Kirby',
        'Easter Bunny',
        'Nutella',
        'Superman',
        'Yoda',
        'Zelda',
        'India',
        'Scotland',
        'Zuma',
        'iPad',
        'Popeye',
        'Xerox',
        'McDonalds',
        'Eminem',
        'Wonder Woman',
        'The Beatles',
        'William Shakespeare',
        'Dumbo',
        'Playstation',
        'Photoshop',
        'Bitcoin',
        'Star Wars',
        'Rome',
        'Morse code',
        'Nike',
        'Sherlock Holmes',
        'Egypt',
        'Singapore',
        'Gru',
        'Bart Simpson',
        'Gumball',
        'Pinocchio',
        'Netherlands',
        'Picasso',
        'Microsoft',
        'Creeper',
        'Samsung',
        'Las Vegas',
        'Leonardo DiCaprio',
        'Mount Rushmore',
        'Mickey Mouse',
        'Homer Simpson',
        'Abraham Lincoln',
        'Hello Kitty',
        'Wolverine',
        'Minecraft',
        'Romania',
        'Gandhi',
        'Cerberus',
        'Angelina Jolie',
        'Hawaii',
        'W-LAN',
        'Adidas',
        'Jesus Christ',
        'Einstein',
        'Porky Pig',
        'China',
        'Skrillex',
        'MTV',
        'Canada',
        'SpongeBob',
        'Spiderman',
        'Monday',
        'Bomberman',
        'Crash Bandicoot',
        'Usain Bolt',
        'Pink Panther',
        'Wall-e',
        'Android',
        'Cupid',
        'Lego',
        'Mona Lisa',
        'Zorro',
        'Teletubby',
        'WhatsApp',
        'Easter',
        'Finn and Jake',
        'Robin Hood',
        'Mexico',
        'Lasagna',
        'Kim Jong-un',
        'Uranus',
        'Chuck Norris',
        'Tower Bridge',
        'Mr Bean',
        'John Cena',
        'Lion King',
        'Phineas and Ferb',
        'Finn',
        'Norway',
        'Asia',
        'Monster',
        'Obelix',
        'Jimmy Neutron',
        'Spartacus',
        'Portugal',
        'Paypal',
        'Thor',
        'Chewbacca',
        'Olaf',
        'Mount Everest',
        'Atlantis',
        'NASCAR',
        'Big Ben',
        'Squidward',
        'Beethoven',
        'Colosseum',
        'Kung Fu',
        'Youtube',
        'France',
        'Harry Potter',
        'Steam',
        'Argentina',
        'Iron Giant',
        'Pepsi',
        'Greece',
        'Mozart',
        'Saturn',
        'Katy Perry',
        'London',
        'Cuba',
        'Earth',
        'Vault boy',
        'Deadpool',
        'Santa',
        'Vatican',
        'Japan',
        'Stone Age',
        'Dracula',
        'Lady Gaga',
        'Audi',
        'Neptune',
        'Russia',
        'Statue of Liberty',
        'Europe',
        'Home Alone',
        'Cat Woman',
        'Captain America',
        'Intel',
        'Eiffel tower',
        'Pluto',
        'Tarzan',
        'God',
        'Oreo',
        'Nintendo Switch',
        'Yoshi',
        'BMX',
        'North Korea',
        'Mummy',
        'Jack-o-lantern',
        'Sonic',
        'Fred Flintstone',
        'DNA',
        'Croatia',
        'Hula Hoop',
        'Michael Jackson',
        'Black Friday',
        'Doritos',
        'Minotaur',
        'Reddit',
        'Pikachu',
        'Excalibur',
        'Elmo',
        'Mars',
        'Anubis',
        'Asterix',
        'Goofy',
        'Tower of Pisa',
        'Jenga',
        'Tetris',
        'ABBA',
        'iPhone',
        'Susan Wojcicki',
        'Pac-Man',
        'Green Lantern',
        'Capricorn',
        'Titanic',
        'Luigi',
        'Winnie the Pooh',
        'Gandalf',
        'Charlie Chaplin',
        'Johnny Bravo',
        'Notch',
        'Mario',
        'KFC',
        'Brazil',
        'Nasa',
        'Bruce Lee',
        'Segway',
        'Poseidon',
        'Skittles',
        'Miniclip',
        'Leonardo da Vinci',
        'Mr. Meeseeks',
        'Bible',
        'Pringles',
        'Northern Lights',
        'Mont Blanc',
        'Bugs Bunny',
        'England',
        'Mr. Bean',
        'Velociraptor',
        'UFO',
        'Sudoku',
        'King Kong',
        'USB',
        'Darwin Watterson',
        'Madagascar',
        'Morty',
        'Hercules',
        'Solar System',
        'Slinky',
        'Paris',
        'Mr Meeseeks',
        'Chinatown',
        'Spain',
        'Stegosaurus',
        'Family Guy',
        'T-rex',
        'Band-Aid',
        'Chrome',
        'Yin and Yang',
        'Venus',
        'Florida',
        'Milky Way',
    ];
}
